backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "issues"
    label: "Issue Templates"
    folder: "src/issues"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "issue-template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sumary", name: "summary", widget: "text"}
      - {label: "Issue Type", name: "type", widget: "select", options: ["Epic", "Task"]}
      - {label: "Template Group", name: "groups", wigdet: "list"}
